version: '3.8'

services:
  api:
    build: .
    container_name: sentio-api
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=${QDRANT_URL:-https://your-qdrant-instance.cloud}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-your-api-key}
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped 