services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - sentio-net
    volumes:
      - ./.fallback_cache:/app/.fallback_cache
    working_dir: /app
    environment:
      - QDRANT_URL=${QDRANT_URL:-https://your-qdrant-instance.cloud}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-your-api-key}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://sentio-ui:8501,http://localhost:8501

  sentio-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: sentio-ui
    ports:
      - "8501:8501"
    environment:
      - SENTIO_BACKEND_URL=http://api:8000
    networks:
      - sentio-net

networks:
  sentio-net:
    driver: bridge
