apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: sentio-rag
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: vector-store
    app.kubernetes.io/part-of: sentio-rag-system
spec:
  serviceName: qdrant-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/instance: production
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: production
        app.kubernetes.io/component: vector-store
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.7.4
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        - name: QDRANT__STORAGE__STORAGE_PATH
          value: "/qdrant/storage"
        - name: QDRANT__LOG_LEVEL
          value: "INFO"
        - name: QDRANT__SERVICE__API_KEY
          valueFrom:
            secretKeyRef:
              name: sentio-rag-secrets
              key: QDRANT_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6333
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: sentio-rag
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: vector-store
spec:
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: production
  ports:
  - port: 6333
    targetPort: 6333
    name: http
  - port: 6334
    targetPort: 6334
    name: grpc
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: sentio-rag
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: vector-store
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: production
  ports:
  - port: 6333
    targetPort: 6333
    name: http
  - port: 6334
    targetPort: 6334
    name: grpc